apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "techtrends.fullname" . } }
  namespace: { { .Values.namespace } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { include "techtrends.name" . } }
  template:
    metadata:
      labels:
        app: { { include "techtrends.name" . } }
    spec:
      containers:
        - name: { { include "techtrends.name" . } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: { { .Values.containerPort } }
          resources:
            requests:
              memory: { { .Values.resources.requests.memory } }
              cpu: { { .Values.resources.requests.cpu } }
            limits:
              memory: { { .Values.resources.limits.memory } }
              cpu: { { .Values.resources.limits.cpu } }
          livenessProbe:
            httpGet:
              path: { { .Values.livenessProbe.path } }
              port: { { .Values.containerPort } }
          readinessProbe:
            httpGet:
              path: { { .Values.readinessProbe.path } }
              port: { { .Values.containerPort } }
